# Generated by Django 3.1 on 2021-05-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topsite',
            options={'managed': False},
        ),
    ]
