# Generated by Django 3.1 on 2021-05-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_site', '0002_auto_20210503_1553'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topsite',
            table='top_site',
        ),
    ]
