# Generated by Django 3.1 on 2021-05-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoutAdsl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'cout_adsl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoutFibreOptique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'cout_fibre_optique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoutGoInternetMobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(blank=True, max_length=50, null=True)),
                ('cout', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'cout_go_internet_mobile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LicenceFai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'licence_fai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LicenceGsm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'licence_gsm',
                'managed': False,
            },
        ),
    ]
