# Generated by Django 3.1 on 2021-05-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoutCoupure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_coupure_internet', models.FloatField(blank=True, null=True)),
                ('cout_coupure_facebook', models.FloatField(blank=True, null=True)),
                ('cout_coupure_twitter', models.FloatField(blank=True, null=True)),
                ('cout_coupure_instagram', models.FloatField(blank=True, null=True)),
                ('cout_coupure_whatsapp', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'cout_coupure',
                'managed': False,
            },
        ),
    ]
