# Generated by Django 3.1 on 2021-05-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opendnsv4Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_odr', models.IntegerField(blank=True, null=True)),
                ('save_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'opendnsv4_stat',
                'managed': False,
            },
        ),
    ]
